import React from 'react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { ChevronRight, Lightbulb } from "lucide-react"

interface RecommendationDialogProps {
  reasonings: string[]
  open: boolean
  onOpenChange: (open: boolean) => void
}

const RecommendationDialog = ({
  reasonings,
  open,
  onOpenChange
}: RecommendationDialogProps) => {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl font-semibold text-gray-800 dark:text-gray-100">
            <Lightbulb className="h-5 w-5 text-blue-600" />
            Strategic Recommendations
          </DialogTitle>
          <DialogDescription>
            These are the strategic insights generated by the AI. Note that these can be inaccurate or irrelevant.
          </DialogDescription>
        </DialogHeader>
        
        <div className="mt-6 space-y-4">
          {reasonings.map((reasoning, index) => (
            <div
              key={index}
              className="group flex items-start gap-4 rounded-lg border border-gray-100 bg-white p-4 shadow-sm transition-all hover:border-blue-100 hover:bg-blue-50 dark:border-gray-700 dark:bg-gray-800 dark:hover:border-blue-900 dark:hover:bg-gray-750"
            >
              <div className="flex-shrink-0 rounded-full bg-gradient-to-br from-blue-500 to-blue-600 p-2 text-white shadow-md">
                <span className="flex h-5 w-5 items-center justify-center font-semibold">
                  {index + 1}
                </span>
              </div>
              <div className="flex-1">
                <p className="text-gray-700 dark:text-gray-200">
                  {reasoning}
                </p>
              </div>
              <ChevronRight className="h-5 w-5 text-gray-400 opacity-0 transition-opacity group-hover:opacity-100" />
            </div>
          ))}
          
          {reasonings.length === 0 && (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <Lightbulb className="h-12 w-12 text-gray-300 dark:text-gray-600" />
              <p className="mt-4 text-gray-500 dark:text-gray-400">
                No recommendations available yet.
              </p>
              <p className="text-sm text-gray-400 dark:text-gray-500">
                Click "Ask AI" to generate strategic insights.
              </p>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}

export default RecommendationDialog